apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
      - name: main
        image: invoice-app:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: invoice-app-config
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-app
  labels:
    app: invoice-app
spec:
  type: NodePort
  selector:
    app: invoice-app
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
